# Generated by Django 6.0.4 on 2026-05-20 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='thumbnail_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_thumbnails', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='servicegallery',
            name='image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_galleries', to='media_library.mediaasset'),
        ),
        migrations.AlterField(
            model_name='service',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='services/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='servicegallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/gallery/'),
        ),
    ]
