# Generated by Django 5.2.15 on 2026-06-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cms/team/')),
                ('facebook_url', models.URLField(blank=True, max_length=500)),
                ('twitter_url', models.URLField(blank=True, max_length=500)),
                ('instagram_url', models.URLField(blank=True, max_length=500)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Team members',
                'ordering': ['sort_order'],
            },
        ),
    ]
