# Generated by Django 5.2.15 on 2026-06-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBentoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/services/bento/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('link_anchor', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Service bento cards',
                'ordering': ['sort_order'],
            },
        ),
    ]
