# Generated by Django 6.0.4 on 2026-04-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='request',
            name='service',
            field=models.CharField(choices=[('design', 'Graphic Design'), ('branding', 'Branding'), ('printing', 'Printing'), ('marketing', 'Digital Marketing'), ('video', 'Video Production'), ('training', 'Training')], max_length=100),
        ),
    ]
