# Generated by Django 6.0.4 on 2026-06-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0005_alter_request_status_requestactivity_requestnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units/copies requested'),
        ),
    ]
